name: 3 - Remove from AWS

# Top level permissions of the workflow
permissions: {}

on:
  workflow_dispatch: # Trigger manually

jobs:
  destroy:
    # Destroy resources
    name: Terraform Destroy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        # Checks-out the repository under $GITHUB_WORKSPACE, so follow-up steps can access it
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Terraform
        # Use Terraform specific version
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Configure AWS OIDC credentials
        # Use Github OIDC to authenticate to AWS, assumming role
        id: configure-aws
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ vars.TF_VAR_REGION }}

      - name: Terraform Init
        # Initialize Terraform backend with custom parameters, download providers
        id: terraform-init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TFSTATE_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.TFSTATE_BUCKET_PATH }}" \
            -backend-config="region=${{ vars.TF_VAR_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TFSTATE_TABLE_NAME }}"

      - name: Terraform Destroy
        # Destroy resources
        id: terraform-destroy
        run: |
          terraform destroy -auto-approve  \
            -var="my_own_public_ip=${{ secrets.MY_PUBLIC_IP }}"